services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend'
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DEBUG=${DEBUG}
    ports:
      - "8765:8765"